'use client';

import { useState } from 'react';
import { AppLayout } from '@/components/layout/app-layout';
import { useStore } from '@/lib/store';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  Legend,
} from 'recharts';
import {
  Download,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Package,
  Truck,
  ShoppingCart,
  FileText,
  Calendar,
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import {
  shipmentsChartData,
  revenueChartData,
  counterPerformanceData,
  categoryDistribution,
  dashboardStats,
} from '@/lib/mock-data';

const COLORS = [
  'oklch(0.55 0.18 260)',
  'oklch(0.65 0.15 200)',
  'oklch(0.7 0.14 150)',
  'oklch(0.75 0.12 80)',
];

const CustomTooltip = ({ active, payload, label }: any) => {
  if (active && payload && payload.length) {
    return (
      <div className="rounded-lg border border-border bg-popover p-3 shadow-lg">
        <p className="text-sm font-medium text-foreground mb-1">{label}</p>
        {payload.map((entry: any, index: number) => (
          <p key={index} className="text-sm text-muted-foreground">
            {entry.name}:{' '}
            <span className="font-medium text-foreground">
              {entry.name.toLowerCase().includes('revenue')
                ? `$${entry.value.toLocaleString()}`
                : entry.value.toLocaleString()}
            </span>
          </p>
        ))}
      </div>
    );
  }
  return null;
};

// Extended mock data for reports
const monthlySalesData = [
  { month: 'Jan', sales: 125000, orders: 312, avgOrder: 400 },
  { month: 'Feb', sales: 142000, orders: 355, avgOrder: 400 },
  { month: 'Mar', sales: 168000, orders: 420, avgOrder: 400 },
  { month: 'Apr', sales: 195000, orders: 487, avgOrder: 400 },
  { month: 'May', sales: 215000, orders: 537, avgOrder: 400 },
  { month: 'Jun', sales: 248000, orders: 620, avgOrder: 400 },
];

const shipmentPerformance = [
  { metric: 'On-Time Delivery', value: 94, target: 95 },
  { metric: 'First Attempt Success', value: 87, target: 90 },
  { metric: 'Customer Satisfaction', value: 92, target: 90 },
  { metric: 'Return Rate', value: 3, target: 5 },
];

const inventoryTurnover = [
  { category: 'Electronics', turnover: 8.5, avgDays: 43 },
  { category: 'Furniture', turnover: 4.2, avgDays: 87 },
  { category: 'Supplies', turnover: 12.3, avgDays: 30 },
];

export default function ReportsPage() {
  const { orders, products, shipments, counters } = useStore();
  const [dateRange, setDateRange] = useState('6m');

  const totalRevenue = orders.reduce((sum, o) => sum + o.total, 0);
  const avgOrderValue = totalRevenue / orders.length;
  const deliveredShipments = shipments.filter((s) => s.status === 'delivered').length;
  const deliveryRate = (deliveredShipments / shipments.length) * 100;

  const exportToPDF = (reportType: string) => {
    const doc = new jsPDF();
    
    doc.setFontSize(24);
    doc.setTextColor(85, 85, 85);
    doc.text(`${reportType} Report`, 20, 30);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('CVG Logistics - Analytics Report', 20, 40);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 46);
    
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text('Summary Statistics', 20, 65);
    
    doc.setFontSize(10);
    let y = 75;
    
    if (reportType === 'Sales') {
      doc.text(`Total Revenue: $${totalRevenue.toLocaleString()}`, 25, y);
      doc.text(`Total Orders: ${orders.length}`, 25, y + 8);
      doc.text(`Average Order Value: $${avgOrderValue.toFixed(2)}`, 25, y + 16);
    } else if (reportType === 'Shipment') {
      doc.text(`Total Shipments: ${shipments.length}`, 25, y);
      doc.text(`Delivered: ${deliveredShipments}`, 25, y + 8);
      doc.text(`Delivery Rate: ${deliveryRate.toFixed(1)}%`, 25, y + 16);
    } else if (reportType === 'Inventory') {
      doc.text(`Total Products: ${products.length}`, 25, y);
      const lowStock = products.filter((p) => p.status === 'low_stock').length;
      const outOfStock = products.filter((p) => p.status === 'out_of_stock').length;
      doc.text(`Low Stock Items: ${lowStock}`, 25, y + 8);
      doc.text(`Out of Stock Items: ${outOfStock}`, 25, y + 16);
    }
    
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('This report is generated by CVG Logistics Management System', 20, 280);
    
    doc.save(`${reportType.toLowerCase()}-report-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const exportToCSV = (data: any[], filename: string) => {
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map((row) => Object.values(row).join(',')).join('\n');
    const csv = `${headers}\n${rows}`;
    
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AppLayout title="Reports & Analytics" subtitle="Comprehensive business insights and performance metrics">
      {/* Header Actions */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <Calendar className="h-5 w-5 text-muted-foreground" />
          <Select value={dateRange} onValueChange={setDateRange}>
            <SelectTrigger className="w-40">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1m">Last Month</SelectItem>
              <SelectItem value="3m">Last 3 Months</SelectItem>
              <SelectItem value="6m">Last 6 Months</SelectItem>
              <SelectItem value="1y">Last Year</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6">
        <Card className="border-border/50">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardDescription>Total Revenue</CardDescription>
            <DollarSign className="h-5 w-5 text-success" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${(totalRevenue / 1000).toFixed(0)}K</div>
            <div className="flex items-center gap-1 text-sm text-success mt-1">
              <TrendingUp className="h-4 w-4" />
              <span>+{dashboardStats.revenueChange}% vs last period</span>
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/50">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardDescription>Total Orders</CardDescription>
            <ShoppingCart className="h-5 w-5 text-chart-1" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{dashboardStats.totalOrders}</div>
            <div className="flex items-center gap-1 text-sm text-success mt-1">
              <TrendingUp className="h-4 w-4" />
              <span>+{dashboardStats.ordersChange}% vs last period</span>
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/50">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardDescription>Delivery Rate</CardDescription>
            <Truck className="h-5 w-5 text-chart-2" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{deliveryRate.toFixed(1)}%</div>
            <div className="flex items-center gap-1 text-sm text-success mt-1">
              <TrendingUp className="h-4 w-4" />
              <span>+{dashboardStats.deliveredChange}% vs last period</span>
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/50">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardDescription>Avg Order Value</CardDescription>
            <FileText className="h-5 w-5 text-chart-4" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${avgOrderValue.toFixed(0)}</div>
            <div className="flex items-center gap-1 text-sm text-muted-foreground mt-1">
              <span>Based on {orders.length} orders</span>
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="sales" className="space-y-6">
        <TabsList className="grid w-full grid-cols-3 max-w-md">
          <TabsTrigger value="sales">Sales Report</TabsTrigger>
          <TabsTrigger value="shipment">Shipments</TabsTrigger>
          <TabsTrigger value="inventory">Inventory</TabsTrigger>
        </TabsList>

        {/* Sales Report Tab */}
        <TabsContent value="sales" className="space-y-6">
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => exportToCSV(monthlySalesData, 'sales-report')}>
              <Download className="mr-2 h-4 w-4" />
              Export CSV
            </Button>
            <Button onClick={() => exportToPDF('Sales')}>
              <FileText className="mr-2 h-4 w-4" />
              Export PDF
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            {/* Revenue Trend */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Revenue Trend</CardTitle>
                <CardDescription>Monthly revenue over time</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <AreaChart data={revenueChartData}>
                    <defs>
                      <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="oklch(0.55 0.18 260)" stopOpacity={0.3} />
                        <stop offset="95%" stopColor="oklch(0.55 0.18 260)" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border/50" />
                    <XAxis dataKey="name" tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} />
                    <YAxis tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} tickFormatter={(v) => `$${v/1000}k`} />
                    <Tooltip content={<CustomTooltip />} />
                    <Area type="monotone" dataKey="revenue" stroke="oklch(0.55 0.18 260)" strokeWidth={2} fill="url(#colorRev)" />
                  </AreaChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Orders vs Shipments */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Orders vs Shipments</CardTitle>
                <CardDescription>Comparison of orders and shipments</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <LineChart data={shipmentsChartData}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border/50" />
                    <XAxis dataKey="name" tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} />
                    <YAxis tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                    <Line type="monotone" dataKey="orders" stroke="oklch(0.55 0.18 260)" strokeWidth={2} dot={{ fill: 'oklch(0.55 0.18 260)' }} />
                    <Line type="monotone" dataKey="shipments" stroke="oklch(0.65 0.15 200)" strokeWidth={2} dot={{ fill: 'oklch(0.65 0.15 200)' }} />
                  </LineChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Counter Performance */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Counter Performance</CardTitle>
                <CardDescription>Revenue by counter location</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={counterPerformanceData} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border/50" />
                    <XAxis type="number" tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} tickFormatter={(v) => `$${v/1000}k`} />
                    <YAxis dataKey="name" type="category" tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} width={100} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="revenue" fill="oklch(0.55 0.18 260)" radius={[0, 8, 8, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Category Distribution */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Sales by Category</CardTitle>
                <CardDescription>Distribution of sales across categories</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={categoryDistribution}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={5}
                      dataKey="value"
                      label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    >
                      {categoryDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip content={<CustomTooltip />} />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Shipment Report Tab */}
        <TabsContent value="shipment" className="space-y-6">
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => exportToCSV(shipmentPerformance, 'shipment-report')}>
              <Download className="mr-2 h-4 w-4" />
              Export CSV
            </Button>
            <Button onClick={() => exportToPDF('Shipment')}>
              <FileText className="mr-2 h-4 w-4" />
              Export PDF
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            {/* Shipment Performance Metrics */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Performance Metrics</CardTitle>
                <CardDescription>Key shipment performance indicators</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {shipmentPerformance.map((metric) => (
                    <div key={metric.metric} className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium">{metric.metric}</span>
                        <span className={`text-sm font-bold ${metric.value >= metric.target ? 'text-success' : 'text-warning'}`}>
                          {metric.value}%
                        </span>
                      </div>
                      <div className="h-2 bg-secondary rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full transition-all ${metric.value >= metric.target ? 'bg-success' : 'bg-warning'}`}
                          style={{ width: `${Math.min(metric.value, 100)}%` }}
                        />
                      </div>
                      <p className="text-xs text-muted-foreground">Target: {metric.target}%</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Shipment Status Distribution */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Shipment Status</CardTitle>
                <CardDescription>Current status distribution</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={[
                        { name: 'Delivered', value: shipments.filter((s) => s.status === 'delivered').length },
                        { name: 'In Transit', value: shipments.filter((s) => s.status === 'in_transit').length },
                        { name: 'Out for Delivery', value: shipments.filter((s) => s.status === 'out_for_delivery').length },
                        { name: 'Preparing', value: shipments.filter((s) => s.status === 'preparing').length },
                      ]}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      {[0, 1, 2, 3].map((index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Inventory Report Tab */}
        <TabsContent value="inventory" className="space-y-6">
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => exportToCSV(inventoryTurnover, 'inventory-report')}>
              <Download className="mr-2 h-4 w-4" />
              Export CSV
            </Button>
            <Button onClick={() => exportToPDF('Inventory')}>
              <FileText className="mr-2 h-4 w-4" />
              Export PDF
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            {/* Stock Status */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Stock Status Overview</CardTitle>
                <CardDescription>Current inventory health</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={[
                        { name: 'In Stock', value: products.filter((p) => p.status === 'in_stock').length },
                        { name: 'Low Stock', value: products.filter((p) => p.status === 'low_stock').length },
                        { name: 'Out of Stock', value: products.filter((p) => p.status === 'out_of_stock').length },
                      ]}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      <Cell fill="oklch(0.65 0.18 150)" />
                      <Cell fill="oklch(0.75 0.15 80)" />
                      <Cell fill="oklch(0.6 0.2 25)" />
                    </Pie>
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Inventory Turnover */}
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle>Inventory Turnover</CardTitle>
                <CardDescription>Category turnover rates</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-6 pt-4">
                  {inventoryTurnover.map((item) => (
                    <div key={item.category} className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{item.category}</span>
                        <div className="text-right">
                          <span className="text-lg font-bold">{item.turnover}x</span>
                          <p className="text-xs text-muted-foreground">{item.avgDays} days avg</p>
                        </div>
                      </div>
                      <div className="h-3 bg-secondary rounded-full overflow-hidden">
                        <div
                          className="h-full bg-gradient-to-r from-primary to-chart-2 rounded-full transition-all"
                          style={{ width: `${(item.turnover / 15) * 100}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Products by Category */}
            <Card className="border-border/50 lg:col-span-2">
              <CardHeader>
                <CardTitle>Products by Category</CardTitle>
                <CardDescription>Stock levels across categories</CardDescription>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={categoryDistribution}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border/50" />
                    <XAxis dataKey="name" tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} />
                    <YAxis tick={{ fill: 'oklch(0.45 0.02 260)', fontSize: 12 }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                      {categoryDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </AppLayout>
  );
}
